# Generated by Django 3.0.7 on 2020-06-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200617_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
